// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: stream/http/v1/http.proto

package httpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_stream_http_v1_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_stream_http_v1_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_stream_http_v1_http_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_stream_http_v1_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_stream_http_v1_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_stream_http_v1_http_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stream_http_v1_http_proto protoreflect.FileDescriptor

const file_stream_http_v1_http_proto_rawDesc = "" +
	"\n" +
	"\x19stream/http/v1/http.proto\x12\x0estream.http.v1\"1\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x96\x01\n" +
	"\x12com.stream.http.v1B\tHttpProtoP\x01Z\x1bproto/stream/http/v1;httpv1\xa2\x02\x03SHX\xaa\x02\x0eStream.Http.V1\xca\x02\x0eStream\\Http\\V1\xe2\x02\x1aStream\\Http\\V1\\GPBMetadata\xea\x02\x10Stream::Http::V1b\x06proto3"

var (
	file_stream_http_v1_http_proto_rawDescOnce sync.Once
	file_stream_http_v1_http_proto_rawDescData []byte
)

func file_stream_http_v1_http_proto_rawDescGZIP() []byte {
	file_stream_http_v1_http_proto_rawDescOnce.Do(func() {
		file_stream_http_v1_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_http_v1_http_proto_rawDesc), len(file_stream_http_v1_http_proto_rawDesc)))
	})
	return file_stream_http_v1_http_proto_rawDescData
}

var file_stream_http_v1_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_http_v1_http_proto_goTypes = []any{
	(*Request)(nil),  // 0: stream.http.v1.Request
	(*Response)(nil), // 1: stream.http.v1.Response
}
var file_stream_http_v1_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_http_v1_http_proto_init() }
func file_stream_http_v1_http_proto_init() {
	if File_stream_http_v1_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_http_v1_http_proto_rawDesc), len(file_stream_http_v1_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_http_v1_http_proto_goTypes,
		DependencyIndexes: file_stream_http_v1_http_proto_depIdxs,
		MessageInfos:      file_stream_http_v1_http_proto_msgTypes,
	}.Build()
	File_stream_http_v1_http_proto = out.File
	file_stream_http_v1_http_proto_goTypes = nil
	file_stream_http_v1_http_proto_depIdxs = nil
}
