// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: stream/alias/v1/uuid.proto

package aliasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_stream_alias_v1_uuid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_stream_alias_v1_uuid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_stream_alias_v1_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_stream_alias_v1_uuid_proto protoreflect.FileDescriptor

const file_stream_alias_v1_uuid_proto_rawDesc = "" +
	"\n" +
	"\x1astream/alias/v1/uuid.proto\x12\x0fstream.alias.v1\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\x9d\x01\n" +
	"\x13com.stream.alias.v1B\tUuidProtoP\x01Z\x1dproto/stream/alias/v1;aliasv1\xa2\x02\x03SAX\xaa\x02\x0fStream.Alias.V1\xca\x02\x0fStream\\Alias\\V1\xe2\x02\x1bStream\\Alias\\V1\\GPBMetadata\xea\x02\x11Stream::Alias::V1b\x06proto3"

var (
	file_stream_alias_v1_uuid_proto_rawDescOnce sync.Once
	file_stream_alias_v1_uuid_proto_rawDescData []byte
)

func file_stream_alias_v1_uuid_proto_rawDescGZIP() []byte {
	file_stream_alias_v1_uuid_proto_rawDescOnce.Do(func() {
		file_stream_alias_v1_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_alias_v1_uuid_proto_rawDesc), len(file_stream_alias_v1_uuid_proto_rawDesc)))
	})
	return file_stream_alias_v1_uuid_proto_rawDescData
}

var file_stream_alias_v1_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stream_alias_v1_uuid_proto_goTypes = []any{
	(*UUID)(nil), // 0: stream.alias.v1.UUID
}
var file_stream_alias_v1_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_alias_v1_uuid_proto_init() }
func file_stream_alias_v1_uuid_proto_init() {
	if File_stream_alias_v1_uuid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_alias_v1_uuid_proto_rawDesc), len(file_stream_alias_v1_uuid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_alias_v1_uuid_proto_goTypes,
		DependencyIndexes: file_stream_alias_v1_uuid_proto_depIdxs,
		MessageInfos:      file_stream_alias_v1_uuid_proto_msgTypes,
	}.Build()
	File_stream_alias_v1_uuid_proto = out.File
	file_stream_alias_v1_uuid_proto_goTypes = nil
	file_stream_alias_v1_uuid_proto_depIdxs = nil
}
