name: Release

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created }}
      changes: ${{ steps.identify_changes.outputs.src_count }}

    steps:
      - name: Release
        id: release
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          package-name: schema-registry-go
          version-file: version.txt
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true