name: Release

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_number: ${{ steps.get_pr_number.outputs.pr_number }}

    steps:
      - name: Release
        id: release
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          package-name: schema-registry-go
          version-file: version.txt
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true


      - name: Dump raw PR JSON
        run: |
          echo "====== RAW PR JSON BEGIN ======"
          echo "${{ fromJSON(steps.release.outputs.pr) }}"
          echo "======= RAW PR JSON END ======="

      - name: Get Release PR Number
        id: get_pr_number
        run: |
          PR_NUMBER=${{ fromJSON(steps.release.outputs.pr).number }}
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
      
      - name: Debug
        id: debug
        run: |
          echo "${{steps.get_pr_number.outputs.pr_number}}"
          
  merge-release:
    name: Merge Release
    runs-on: ubuntu-latest
    if: ${{ !needs.release-please.outputs.release_created && needs.release-please.outputs.release_number > 0 }}
    needs: release-please

    steps:
    - name: Merge PR
      id: merge
      run: gh pr merge ${{ needs.release-please.outputs.release_number }} --merge --auto --delete-branch
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}