name: Watch Registry Schema Changes

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
#on:
#  repository_dispatch:
#    types: [EVENT_SCHEMA_REGISTRY_PULL_NEW_CHANGES]

jobs:
  update_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          commit-message: Update report
          branch: example-patches
          title: '[Example] Update report'
          base: main
          sign-commits: true
